### ISSUE TITLE
Collaborate with blockstagram

### ISSUE THREAD

**Issue by friedger** [recall-photos/recall-app#1]
There is an app called blockstagram https://github.com/coding-berlin/blockstagram that handles photo sharing....

**Comment by alvesjtiago** [comment]
Hi @friedger, thanks for letting us know about Blockstagram. It doesn't seem to be deployed anywhere though. What would be your thoughts on collaboration? Thanks

**Comment by jackveiga** [comment]
Closing the issue since some time has passed and the discussion has stopped.
