### ISSUE TITLE
Feedback to improve text copy on homepage

### ISSUE THREAD

**Issue by jackveiga** [recall-photos/recall-app#13]
![feedback](https://user-images.githubusercontent.com/215726/55090623-68a93600-50ea-11e9-92f8-23e89b46758a.png)

We received this feedback on Blockstack's Slack when we revamped the home page design on #6

**Comment by alvesjtiago** [comment]
@jackveiga what do you think about changing the first message to:

```To start using Recall, you need to create a free and instantly available account with Blockstack. This is your personal identity on the new web. Learn more about it <a href="https://blockstack.org/">here</a>.```

And the second one to:

```After you have your ID, you will need to authorize Recall to write on your hub (provided freely by Blockstack). Think of your hub as your personal and secure space that only you can access.```

**Comment by jackveiga** [comment]
Sounds good to me!
