### ISSUE TITLE
Mass import photos to recall?

### ISSUE THREAD

**Issue by redandvidya** [recall-photos/recall-app#46]
Hi, I downloaded this app because I'm always on the lookout for more open-source projects to support. I want to try moving all of my photo and video library on recall, but as of right now, on my iPhone I have to do it individually. Will this feature be implemented soon?

**Comment by alvesjtiago** [comment]
Hi @redandvidya, thanks for you support. The auto import feature is currently under development. It will hopefully be available on the next version of the app.

**Comment by alvesjtiago** [comment]
This issue is being tracked on the recall-ios repo so you can follow it at https://github.com/recall-photos/recall-ios/issues/5. I'm going to close this issue but if you have any questions or comments please feel free to comment on the mentioned issue.
