### ISSUE TITLE
Sign in link does not work on firefox

### ISSUE THREAD

**Issue by D4nte** [recall-photos/recall-app#5]
I am not able to sign in in Firefox at https://app.recall.photos/ (Mac OS)

No problem with chrome. I cannot see much in the logs:

```
[INFO] blockstack.js: generating v1.3.1 auth request logger.js:46
openUriUsingFirefox index.js:207
[INFO] protocol handler detected logger.js:46
```

**Comment by alvesjtiago** [comment]
Hi @D4nte, I've just tried it on Firefox 61.0.2 and it worked. What version are you using?

**Comment by D4nte** [comment]
I use 64.0
I have the following extensions, maybe one them is an issue, I tried deactivating and no luck:
- multi-containers
- https everywhere
- adblock plus
- Privacy Badger

**Comment by D4nte** [comment]
Hi, I am logged in https://browser.blockstack.org/profiles from firefox (ie, no blockstack app installed)
Nothing happened when clicking on the button (well, we can see the animation as if the button was pushed but that's pretty much it).

Let me know what I can do to help you debug it.

**Comment by hstove** [comment]
Unfortunately, logging in with Blockstack doesn't work on Firefox if you don't have the native Blockstack Browser app installed (https://blockstack.org/install/). We have a fix in-progress that will support Firefox login without the native app, but it's not ready yet.

**Comment by D4nte** [comment]
great, thanks for letting me know!
