### ISSUE TITLE
Download button does not work in Firefox

### ISSUE THREAD

**Issue by shjryan** [recall-photos/recall-app#50]
### Browsers

Chrome version: 76.0.3809.100 (Official Build) (64-bit)
Firefox version: 68.0.2 (64-bit)

Chrome works as expected
Firefox does not work as expected

### Issue

Firefox needs anchor object to be appended to the document.body before click.  This seems like a browser specific behaviour that Chrome doesn't care about.

### Other issues

- error emitted from `orientation-exif-blob` referencing a forked version of `exif-js`, which does not include `xml2json` function
- Edge needs a polyfill of `toBlob`

**Comment by alvesjtiago** [comment]
Fixed by https://github.com/recall-photos/recall-app/pull/51

**Comment by alvesjtiago** [comment]
Thank you @shjryan!
