### ISSUE TITLE
🤓 Make the readme clearer and nicer

### ISSUE THREAD

**Issue by jackveiga** [recall-photos/recall-app#7]
Readme could be arranged nicer

**Comment by alvesjtiago** [comment]
@jackveiga should we add the landing page image to the readme instead of the current dashboard? Also we should change the Trello board link to the Projects roadmap on github and describe Recall a little better. Anything else that you feel it's missing?

**Comment by jackveiga** [comment]
I don't know if showing the dashboard makes more sense, since its what you eventually use in the app. Agree with adding the roadmap and a better description of what Recall does and is trying to achieve. I think that we should also add a link to blockstack and add a license disclaimer at the end.

**Comment by jackveiga** [comment]
- [ ] Add license
- [ ] Update image on readme
- [ ] Add roadmap
- [ ] How to access discord
- [ ] How to leave an issue for new features
- [ ] Add link to Blockstack
- [ ] Contribute to translation?

@alvesjtiago would you change or add anything to the above list?

**Comment by alvesjtiago** [comment]
Sounds great. Let's do that 👌

**Comment by jackveiga** [comment]
We still missing some stuff from the updated readme but think we can skip that for now, so closing.
